const ROUTE_CONSTANTS = {
  HOME: "/",
  LOGIN: "login",
  SIGNUP: "signup",
  DASHBOARD: "dashboard",
  SETTINGS: "settings",
  PROFILE: "profile",
  ADMIN: "admin",
  USER: "user",
  FORGOT_PASSWORD: "forgot-password",
  RESET_PASSWORD: "reset-password",
  NOT_FOUND: "/404",
  SERVER_ERROR: "/500",
  UNAUTHORIZED: "/401",
  FORBIDDEN: "/403",
  CONTACT_US: "contact-us",
  TERMS_OF_SERVICE: "terms-of-service",
  PRIVACY_POLICY: "privacy-policy",
  FAQ: "faq",
  HELP: "help",
  BLOG: "blog",
  ABOUT_US: "about-us",
  CREATE_POST: "create-post",
  EDIT_POST: "edit-post:id",
};

export default ROUTE_CONSTANTS;
